rm(list = ls())

library(tidyverse)

load("C:/Users/fallouch/Box/PhD/CHERISH/CHERISH/deidRaw/input/cherish.RData")

cherish <- cherish %>% 
  mutate(q1 = ifelse(a_and_choose_one == 1, q1 / 365.25,
                     ifelse(a_and_choose_one == 2, ((q1 * 7) / 365.25),
                            ifelse(a_and_choose_one == 3, ((q1 * 30.42) / 365.25), q1)))) %>%  # transforming all times to years
  select(-c(a_there_are_walkable_sidew,
         b_there_are_facilities_to,
         c_my_neighborhood_has_free,
         d_there_are_many_shops_sto,
         e_a_large_selection_of_fre,
         a_people_around_here_are_w,
         b_people_in_my_neighborhoo,
         c_people_in_my_neighborhoo,
         d_people_in_my_neighborhoo,
         e_i_feel_safe_walking_in_m,
         f_violence_is_a_problem_in,
         q4,
         q5,
         q6,
         a,
         q7,
         q7a,
         q8,
         q8a,
         q9,
         q9a,
         q10,
         q11,
         q12,
         q13,
         q14,
         q15,
         q16,
         q17,
         q17a___1,
         q17a___2,
         q17a___3,
         q17a___4,
         q17a___5,
         a_asking_questions_to_your,
         c_understanding_medical_tr,
         q19___1,
         q19___2,
         q19___3,
         q19___4,
         q19___5,
         q20,
         q21___1,
         q21___2,
         q21___3,
         q21___4,
         q21___5,
         q21___6,
         q21___7,
         q21___8,
         q21___9,
         q22___1,
         q22___2,
         q22___3,
         q22___4,
         q22___5,
         q22___6,
         a_sometimes_doctors_care_m,
         b_doctor_are_extremely_tho,
         c_you_completely_trust_doc,
         d_a_doctor_would_never_mis,
         e_all_in_all_you_have_comp,
         a_religious_spiritual_beli,
         b_i_tend_to_avoid_things_h,
         a_medical_researchers_have,
         b_it_is_safe_to_be_in_a_me,
         c_there_are_some_things_ab,
         d_medical_researchers_do_n,
         a_i_think_being_connected,
         b_i_think_receiving_health,
         c_i_think_participating_in,
         d_i_think_participating_in,
         e_i_think_measuring_my_blo,
         q29,
         q30,
         q31,
         q32,
         q33,
         q34,
         cherish_survey_complete,
         cherish_survey_complete.factor,
         a_and_choose_one,
         a_and_choose_one.factor,
         b_traveling_to_medical_app)) %>% 
  mutate(q17a.factor = as.factor(case_when(q17a___1.factor == "Checked" ~ 1,
                                           q17a___2.factor == "Checked" ~ 2,
                                           q17a___3.factor == "Checked" ~ 3,
                                           q17a___4.factor == "Checked" ~ 4,
                                           q17a___5.factor == "Checked" ~ 5)),
         q19.factor = as.factor(case_when(q19___1.factor == "Checked" ~ 1,
                                          q19___2.factor == "Checked" ~ 2,
                                          q19___3.factor == "Checked" ~ 3,
                                          q19___4.factor == "Checked" ~ 4,
                                          q19___5.factor == "Checked" ~ 5)),
         q21.factor = as.factor(case_when(q21___1.factor == "Checked" ~ 1,
                                          q21___2.factor == "Checked" ~ 2,
                                          q21___3.factor == "Checked" ~ 3,
                                          q21___4.factor == "Checked" ~ 4,
                                          q21___5.factor == "Checked" ~ 5,
                                          q21___6.factor == "Checked" ~ 6,
                                          q21___7.factor == "Checked" ~ 7,
                                          q21___8.factor == "Checked" ~ 8,
                                          q21___9.factor == "Checked" ~ 9)),
         q22.factor = as.factor(case_when(q22___1.factor == "Checked" ~ 1,
                                          q22___2.factor == "Checked" ~ 2,
                                          q22___3.factor == "Checked" ~ 3,
                                          q22___4.factor == "Checked" ~ 4,
                                          q22___5.factor == "Checked" ~ 5,
                                          q22___6.factor == "Checked" ~ 6)))
           
library(labelled)

var_label(cherish) <- list(q1 = "How long have you lived in your current neighborhood? (years)",
                           a_there_are_walkable_sidew.factor = "There are walkable sidewalks on most of the streets in my neighborhood",
                           b_there_are_facilities_to.factor = "There are facilities to bicycle in or near my neighborhood, such as special lanes, separate paths or trails, shared use paths for cycles and pedestrians",
                           c_my_neighborhood_has_free.factor = "My neighborhood has free or low-cost recreation facilities, such as parks, walking trails, bike paths, recreation centers, playgrounds, public swimming pools, etc.",
                           d_there_are_many_shops_sto.factor = "There are many shops, stores, markets, or other places to buy things I need within easy walking distance",
                           e_a_large_selection_of_fre.factor = "A large selection of fresh fruits and vegetables is available in my neighborhood",
                           a_people_around_here_are_w.factor = "People around here are willing to help their neighbors",
                           b_people_in_my_neighborhoo.factor = "People in my neighborhood generally get along with each other",
                           c_people_in_my_neighborhoo.factor = "People in my neighborhood can be trusted",
                           d_people_in_my_neighborhoo.factor = "People in my neighborhood share the same values",
                           e_i_feel_safe_walking_in_m.factor = "I feel safe walking in my neighborhood, day or night",
                           f_violence_is_a_problem_in.factor = "Violence is a problem in my neighborhood",
                           q4.factor = "In the past 3 months, how often have you worried that your food would run out before you had money to buy more?",
                           q5.factor = "Are you easily able to get enough healthy food to eat? (i.e., fruits, vegetables etc.)",
                           q6.factor = "Do you usually eat fruits and vegetables every day?",
                           a.factor = "Are you willing to eat more fruits and vegetables?",
                           q7.factor = "Do you do any physical activity?",
                           q7a.factor = "If no, is this something you would be willing to do?",
                           q8.factor = "Do you currently smoke or uses any form of tobacco or nicotine products (i.e. chewing tobacco, vapes, etc.)?",
                           q8a.factor = "If yes are you willing to quit?",
                           q9.factor = "Do you weigh more than you would like to?",
                           q9a.factor = "If yes are you willing to lose weight?",
                           q10.factor	= "Has a doctor or health professional ever told you that you have hypertension or high blood pressure?",
                           q11.factor = "Do you currently take prescribed medication for hypertension or high blood pressure?",
                           q12.factor = "Has a doctor or health professional ever told you that your blood cholesterol level was high?",
                           q13.factor = "Do you currently take prescribed medication for high blood cholesterol?",
                           q14.factor = "Has a doctor or other health professional ever told you (except during pregnancy) that you have diabetes or high blood sugar?",
                           q15.factor = "Are you currently taking your prescribed medication for diabetes?",
                           q16.factor = "Do you take your medications regularly as prescribed?",
                           q17.factor = "(If yes or no to question 16) Are you confident that you can get your medications regularly?",
                           q17a.factor = "If no, why not?",
                           q17a___1.factor = "Have no need for the medication",
                           q17a___2.factor = "Too expensive or lack of insurance",
                           q17a___3.factor = "Pick up is not convenient (location or hours)",
                           q17a___4.factor = "Tend to put it off",
                           q17a___5.factor = "Other",
                           a_asking_questions_to_your.factor = "How confident are you in your ability to ask questions to your health care provider",
                           b_traveling_to_medical_app.factor = "How confident are you in your ability to travel to medical appointments",
                           c_understanding_medical_tr.factor = "How confident are you in your ability to understand medical treatment plans",
                           q19.factor = "Are you currently covered by any of the following types of health insurance or health coverage plans? If you have more than one kind of health insurance, tell me all plans that you have.",
                           q19___1.factor = "Private health insurance",
                           q19___2.factor = "Medicare",
                           q19___3.factor = "Medicaid",
                           q19___4.factor = "Other government insurance",
                           q19___5.factor = "No coverage of any type",
                           q20.factor = "When was the last time you saw a doctor or other health professional for a routine physical, general check-up or treatment for conditions like high blood pressure, cholesterol, or diabetes?",
                           q21.factor = "If you have not seen a doctor or health professional in over a year why? (Check all that apply)",
                           q21___1.factor = "No need for a health care provider",
                           q21___2.factor = "Mistrust or dislike health care providers",
                           q21___3.factor = "Do not know where to go",
                           q21___4.factor = "Previous health care provider is not available or moved",
                           q21___5.factor = "Too expensive or lack of insurance",
                           q21___6.factor = "Care not convenient (location or hours)",
                           q21___7.factor = "Tend to put it off",
                           q21___8.factor = "Concerns about COVID-19",
                           q21___9.factor = "Other",
                           q22.factor = "Where do you go for a general check-up or treatment for conditions such as, high blood pressure, cholesterol, or diabetes?",
                           q22___1.factor = "A doctor's office or health center",
                           q22___2.factor = "Walk-in clinic, urgent care center, or retail clinic in a pharmacy or grocery store",
                           q22___3.factor = "Emergency room",
                           q22___4.factor = "A VA Medical Center or VA outpatient clinic",
                           q22___5.factor = "Some other place",
                           q22___6.factor = "Do not go anywhere",
                           a_sometimes_doctors_care_m.factor = "Sometimes, health care providers care more about what is convenient for (him/her) than about your medical needs.",
                           b_doctor_are_extremely_tho.factor = "Health care providers are extremely thorough and careful",
                           c_you_completely_trust_doc.factor = "You completely trust health care providers decisions about which medical treatments are best",
                           d_a_doctor_would_never_mis.factor = "A health care providers would never mislead you about anything",
                           e_all_in_all_you_have_comp.factor = "All in all, you have complete trust in health care providers",
                           a_religious_spiritual_beli.factor = "Religious/spiritual beliefs have great in􀀄uence on my health",
                           b_i_tend_to_avoid_things_h.factor = "I tend to avoid things harmful to my body because of my religious/spiritual beliefs",
                           a_medical_researchers_have.factor = "Medical Researchers have no selfish reasons for doing research studies",
                           b_it_is_safe_to_be_in_a_me.factor = "It is safe to be in a medical research study",
                           c_there_are_some_things_ab.factor = "There are some things about medical research that I do not trust at all",
                           d_medical_researchers_do_n.factor = "Medical researchers do not tell people everything they really need to know about being in a research study",
                           a_i_think_being_connected.factor = "I think being connected to a primary care provider for routine care is possible for me",
                           b_i_think_receiving_health.factor = "I think receiving health coaching is possible for me",
                           c_i_think_participating_in.factor = "I think participating in exercises classes is possible for me",
                           d_i_think_participating_in.factor = "I think participating in nutrition education classes is possible for me",
                           e_i_think_measuring_my_blo.factor = "I think measuring my blood pressure, glucose, and physical activity at home and recording my values are possible for me",
                           q28 = "How old are you?",
                           q29.factor = "What was your sex assigned at birth?",
                           q30.factor = "Are you of Spanish or Hispanic origin or ancestry?",
                           q31.factor = "What racial group best represents your background?",
                           q32.factor = "What best describes your current marital status?",
                           q33.factor = "What is the highest grade or level of school you have completed or the highest degree you have received?",
                           q34.factor = "We would like to know about what you do-are you working now, looking for work, retired, keeping house, a student, or what?")

save(cherish, file = "C:/Users/fallouch/Box/PhD/CHERISH/CHERISH/deidRaw/output/cherish.RData")




