rm(list = ls())

library(tidyverse)

load("C:/Users/fallouch/Box/PhD/CHERISH/CHERISH/deidRaw/input/cherish.RData")

cherish <- cherish %>% 
  mutate(q1 = ifelse(a_and_choose_one == 1, q1 / 365.25,
                     ifelse(a_and_choose_one == 2, ((q1 * 7) / 365.25),
                            ifelse(a_and_choose_one == 3, ((q1 * 30.42) / 365.25), q1)))) %>%  # transforming all times to years %>% 
  select(-c(a_there_are_walkable_sidew,
         b_there_are_facilities_to,
         c_my_neighborhood_has_free,
         d_there_are_many_shops_sto,
         e_a_large_selection_of_fre,
         a_people_around_here_are_w,
         b_people_in_my_neighborhoo,
         c_people_in_my_neighborhoo,
         d_people_in_my_neighborhoo,
         e_i_feel_safe_walking_in_m,
         f_violence_is_a_problem_in,
         q4,
         q5,
         q6,
         a,
         q7,
         q7a,
         q8,
         q8a,
         q9,
         q9a,
         q10,
         q11,
         q12,
         q13,
         q14,
         q15,
         q16,
         q17,
         q17a___1,
         q17a___2,
         q17a___3,
         q17a___4,
         q17a___5,
         a_asking_questions_to_your,
         c_understanding_medical_tr,
         q19___1,
         q19___2,
         q19___3,
         q19___4,
         q19___5,
         q20,
         q21___1,
         q21___2,
         q21___3,
         q21___4,
         q21___5,
         q21___6,
         q21___7,
         q21___8,
         q21___9,
         q22___1,
         q22___2,
         q22___3,
         q22___4,
         q22___5,
         q22___6,
         a_sometimes_doctors_care_m,
         b_doctor_are_extremely_tho,
         c_you_completely_trust_doc,
         d_a_doctor_would_never_mis,
         e_all_in_all_you_have_comp,
         a_religious_spiritual_beli,
         b_i_tend_to_avoid_things_h,
         a_medical_researchers_have,
         b_it_is_safe_to_be_in_a_me,
         c_there_are_some_things_ab,
         d_medical_researchers_do_n,
         a_i_think_being_connected,
         b_i_think_receiving_health,
         c_i_think_participating_in,
         d_i_think_participating_in,
         e_i_think_measuring_my_blo,
         q29,
         q30,
         q31,
         q32,
         q33,
         q34,
         cherish_survey_complete,
         cherish_survey_complete.factor,
         a_and_choose_one,
         a_and_choose_one.factor,
         b_traveling_to_medical_app))
           
save(cherish, file = "C:/Users/fallouch/Box/PhD/CHERISH/CHERISH/deidRaw/output/cherish.RData")
